name: Android CI

on:
  push:
    branches: [ "main" , "setup_github_action" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run ktlint
      uses: lucasnlm/ktlint-action@v1.0.1

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Run Unit Tests
      run: ./gradlew :app:testDebugUnitTest

    - name: Android Emulator
      uses: vgaidarji/android-github-actions-emulator@v1.0.1

    - name: Run UI Tests
      run: ./gradlew :app:connectedDebugAndroidTest
