name: Android CI

on:
  push:
    branches: [ "main", "setup_github_action" ]
  pull_request:
    branches: [ "main", "setup_github_action" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Java 17 (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Gradle permissions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew :app:testDebugUnitTest

      # Install emulator system image
      - name: Install system image
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            "system-images;android-30;default;x86_64"

      # Create AVD
      - name: Create AVD
        run: echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd --force -n test -k "system-images;android-30;default;x86_64"

      # Start Emulator
      - name: Launch Emulator
        run: |
          nohup emulator -avd test -no-snapshot -no-audio -no-window -gpu swiftshader_indirect &
          adb wait-for-device
          adb shell input keyevent 82

      # Run Instrumented Tests
      - name: Run Instrumented Tests
        run: ./gradlew connectedDebugAndroidTest

      # Publish Test Report
      - name: Android Test Report
        uses: doanpt/AndroidTestReportAction@v1.1
