name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Setup Java 17 (Temurin)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Gradle permissions
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build APK
      - name: Build with Gradle
        run: ./gradlew assembleDebug

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew :app:testDebugUnitTest

      - name: Report
        uses: FlickerSoul/android-test-report-actions@v1.2
        with:
          show-skipped: "true"  # Optional, default to "false"